#encoding=utf-8

ERROR_ACCOUNTLOGIN_INVALID_PWD = u'用户名或密码错误'

ERROR_ACCOUNTREGIST_USERNAME_BLANK = u'用户名不能为空'
ERROR_ACCOUNTREGIST_PWD_BLANK = u'密码不能为空'
ERROR_ACCOUNTREGIST_USERNAME_LENTH_WRONG = u'用户名只能输入6-14个字符'
ERROR_ACCOUNTREGIST_PWD_LENTH_WRONG = u'密码长度为6-16个字符，区分大小写'
ERROR_ACCOUNTREGIST_USERNAME_INVALID_FORMAT_INVALID_STRING = u'用户名只能输入字母、数字和下划线'
ERROR_ACCOUNTREGIST_USERNAME_INVALID_FORMAT_HEAD = u'用户名必须以字母开头'
ERROR_ACCOUNTREGIST_USER_EXIST = u'该用户名已被使用，请重新输入'
