#encoding=utf-8

ERROR_ACCOUNTLOGIN_INVALID_PWD = u'用户名或密码错误'

ERROR_ACCOUNTREGIST_USERNAME_BLANK = u'用户名不能为空'
ERROR_ACCOUNTREGIST_PWD_BLANK = u'密码不能为空'
ERROR_ACCOUNTREGIST_USERNAME_LENTH_WRONG = u'用户名只能输入6-14个字符'
ERROR_ACCOUNTREGIST_PWD_LENTH_WRONG = u'密码长度为6-16个字符，区分大小写'
ERROR_ACCOUNTREGIST_USERNAME_INVALID_FORMAT_INVALID_STRING = u'用户名只能输入字母、数字和下划线'
ERROR_ACCOUNTREGIST_USERNAME_INVALID_FORMAT_HEAD = u'用户名必须以字母开头'
ERROR_ACCOUNTREGIST_USER_EXIST = u'该用户名已被使用，请重新输入'

ERROR_PROFILEPAGE_LONG_NAME = u'姓名不能超过16字符'

ERROR_FORGETPASSWORD_NO_USER_BY_EMAIL = u'该邮箱没有绑定任何账号'
ERROR_FORGETPASSWORD_NO_USER_BY_USERNAME = u'该用户不存在'
ERROR_FORGETPASSWORD_NO_USER_BY_USERNAME_NO_BINDING = u'该用户没有绑定任何邮箱/手机号，无法找回密码'
ERROR_FORGETPASSWORD_NO_USER_BY_SMS = u'该手机号没有绑定任何账号'

ERROR_BINDING_NO_USER = u'该用户不存在'
ERROR_BINDING_BY_PHONE_HAS_BINDED_BY_OTHER = u"该手机号已被其他用户绑定，请重新输入手机号"
ERROR_BINDING_BY_EMAIL_HAS_BINDED_BY_OTHER = u"该邮箱已被其他用户绑定，请重新输入邮箱地址"
ERROR_BINDING_BY_EMAIL_DIFFERENT_BINDED = u"您的账号已绑定了另一个邮箱，请您解绑后再次绑定"
ERROR_BINDING_BY_PHONE_DIFFERENT_BINDED = u"您的账号已绑定了另一个手机号，请您解绑后再次绑定"

ERROR_UNBINDING = u"解除绑定失败，请重新解除绑定"

ERROR_VERIFY = u"该验证码已经失效，请重新获取验证码"
ERROR_VERIFYING_BY_PHONE_HAS_BINDED_BY_OTHER = u"该手机号已被其他用户绑定，请重新输入手机号"
ERROR_VERIFYING_BY_EMAIL_HAS_BINDED_BY_OTHER = u"该邮箱已被其他用户绑定，请重新输入邮箱地址"
ERROR_VERIFYING_WRONG_VERIFIER = "验证码错误"
